collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#020101'
    - '#6E5C4C'
    - '#D8CEC6'
    - '#9B9188'
    - '#428987'
  rhythmicContrast: 1
typography_spectrum: 0.5252951
layout_spectrum: 1
name: JOSH HARNEY PHOTOS
